#!/bin/bash

# Check if exactly 3 arguments are passed
if [ $# -ne 3 ]; then
    echo "Usage: $0 num1 num2 num3"
    exit 1
fi

a=$1
b=$2
c=$3

biggest=$a

if [ $b -gt $biggest ]; then
    biggest=$b
fi

if [ $c -gt $biggest ]; then
    biggest=$c
fi

echo "The biggest number is: $biggest"
